# 基础镜像
FROM redis
# author
MAINTAINER dimple

# 挂载目录
VOLUME /home/dimple/redis
# 创建目录
RUN mkdir -p /home/dimple/redis
# 指定路径
WORKDIR /home/dimple/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/dimple/redis/redis.conf
